import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/withdrawal/pending";

// Generated by https://quicktype.io
export interface Withdrawal {
  withdrawalid: string;
  accountid: string;
  userid: string;
  name: string;
  email: string;
  amount: number;
  approval_status: number | string;
}

export type WithdrawalPendingResponse = {
  data: Withdrawal[];
  message: string;
};

// https://arctfrex.apidog.io/api-10371180
export const useWithdrawalPending = (
  options: UseQueryOptions<WithdrawalPendingResponse, Error> = {
    queryKey: ["withdrawal-pending"],
  }
) => {
  return useQuery({
    queryFn: async () => {
      const { data } = await axios.get<WithdrawalPendingResponse>(ENDPOINT);

      return data;
    },
    ...options,
  });
};
