import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/reports/all";

// Generated by https://quicktype.io

export interface Report {
  code: string;
  name: string;
  description: string;
  is_active: boolean;
  CreatedBy: string;
  CreatedAt: string;
  ModifiedBy: string;
  ModifiedAt: string;
}

export interface ReportAllReponse {
  message: string;
  data: Report[];
  time: string;
}

// https://arctfrex.apidog.io/api-12057240
export const useReportAll = (
  options?: UseQueryOptions<ReportAllReponse, Error>
) => {
  return useQuery({
    ...options,
    queryKey: ["report-all"],
    queryFn: async () => {
      const { data } = await axios.get<ReportAllReponse>(ENDPOINT, {});

      return data;
    },
  });
};
