import { UseMutationOptions, useMutation } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/deposit/pending/approval";

// Generated by https://quicktype.io
export interface DepositPendingApprovalRequest {
  depositid: string;
  deposit_type: number;
  decision: string;
  userlogin: string;
}

// Generated by https://quicktype.io
export interface DepositPendingApprovalResponse {
  message: string;
  data: null;
  time: string;
}

// https://arctfrex.apidog.io/api-10321359
export const useDepositPendingApproval = (
  options: UseMutationOptions<
    DepositPendingApprovalResponse,
    Error,
    DepositPendingApprovalRequest
  >
) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<DepositPendingApprovalResponse>(
        ENDPOINT,
        payload
      );

      return data;
    },
    ...options,
  });
};
