import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";
import { ApprovalStatus } from "@/models/account";

const ENDPOINT = "/backoffice/deposit/pending";

// Generated by https://quicktype.io
interface Deposit {
  depositid: string;
  accountid: string;
  userid: string;
  name: string;
  email: string;
  amount: number;
  bank_name: string;
  bank_account_number: string;
  bank_beneficiary_name: string;
  deposit_photo: string;
  approval_status: ApprovalStatus;
}

export type DepositPendingDetailResponse = {
  data: Deposit;
  message: string;
};

type Options = Partial<UseQueryOptions<DepositPendingDetailResponse, Error>> & {
  depositid?: string;
};

// https://arctfrex.apidog.io/api-10313428
export const useDepositPendingDetail = ({ depositid, ...options }: Options) => {
  return useQuery({
    ...options,
    queryKey: ["deposit-pending-detail", depositid],
    queryFn: async () => {
      const { data } = await axios.get<DepositPendingDetailResponse>(
        ENDPOINT + "/" + depositid
      );

      return data;
    },
  });
};
