import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/account/pending";

// Generated by https://quicktype.io
export interface Account {
  accountid: string;
  userid: string;
  name: string;
  email: string;
  approval_status: number | string;
  dataid: string;
}

export type AccountPendingResponse = {
  data: Account[];
  message: string;
};

// https://arctfrex.apidog.io/api-10321359
export const useAccountPending = (
  options: UseQueryOptions<AccountPendingResponse, Error> = {
    queryKey: ["account-pending"],
  }
) => {
  return useQuery({
    queryFn: async () => {
      const { data } = await axios.get<AccountPendingResponse>(ENDPOINT, {});

      return data;
    },
    ...options,
  });
};
