import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/deposit/pending";

// Generated by https://quicktype.io
export interface Deposit {
  depositid: string;
  accountid: string;
  userid: string;
  name: string;
  email: string;
  amount: number;
  approval_status: number | string;
}

export type DepositPendingResponse = {
  data: Deposit[];
  message: string;
};

// https://arctfrex.apidog.io/api-10371180
export const useDepositPending = (
  options: UseQueryOptions<DepositPendingResponse, Error> = {
    queryKey: ["deposit-pending"],
  }
) => {
  return useQuery({
    queryFn: async () => {
      const { data } = await axios.get<DepositPendingResponse>(ENDPOINT);

      return data;
    },
    ...options,
  });
};
