import { UseMutationOptions, useMutation } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/conversations/sessions";

// Generated by https://quicktype.io
export interface ConversationsSessionIdTakeRequest {
  sessionId: string;
  accessToken: string;
}

// Generated by https://quicktype.io
export interface ConversationsSessionIdTakeResponse {
  message?: string;
  error?: string;
}

export const useConversationsSessionIdTake = (
  options?: UseMutationOptions<
    ConversationsSessionIdTakeResponse,
    Error,
    ConversationsSessionIdTakeRequest
  >
) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { sessionId, accessToken } = payload;

      const { data } = await axios.post<ConversationsSessionIdTakeResponse>(
        ENDPOINT + "/" + sessionId + "/" + "take",
        null,
        {
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        }
      );

      return data;
    },
    ...options,
  });
};
