import {
  UseMutationOptions,
  UseQueryOptions,
  useMutation,
  useQuery,
} from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/emergencycontact";

// Generated by https://quicktype.io
export interface EmergencyContact {
  userid: string;
  emergency_contact_name: string;
  emergency_contact_country: string;
  emergency_contact_province: string;
  emergency_contact_city: string;
  emergency_contact_district: string;
  emergency_contact_subdistrict: string;
  emergency_contact_address: string;
  emergency_contact_phone: string;
  emergency_contact_relation: string;
  is_active: boolean;
  CreatedBy: string;
  CreatedAt: string;
  ModifiedBy: string;
  ModifiedAt: string;
}

export type CustomersUsersEmergencyContactResponse = EmergencyContact;

type Options = Partial<
  UseQueryOptions<CustomersUsersEmergencyContactResponse, Error>
> & {
  userId?: string;
};

// https://arctfrex.apidog.io/api-10313433
export const useCustomersUsersEmergencyContact = ({
  userId,
  ...options
}: Options) => {
  return useQuery({
    ...options,
    queryKey: ["customers-users-emergencyContact", userId],
    queryFn: async () => {
      const { data } = await axios.get<CustomersUsersEmergencyContactResponse>(
        ENDPOINT + "/" + userId
      );

      return data;
    },
  });
};

export const useCustomersUsersEmergencyContactMutation = ({
  userId,
  ...options
}: UseMutationOptions<any, Error, any> & { userId: string }) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<any>(ENDPOINT + "/" + userId, payload);

      return data;
    },
    ...options,
  });
};
