import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/employment";

// Generated by https://quicktype.io
export interface Employment {
  userid: string;
  company_name: string;
  company_address: string;
  company_city: string;
  company_phone: string;
  working_since: string;
  profession: string;
  working_field: string;
  is_active: boolean;
  CreatedBy: string;
  CreatedAt: string;
  ModifiedBy: string;
  ModifiedAt: string;
}

export type CustomersUsersEmploymentResponse = Employment;

type Options = Partial<
  UseQueryOptions<CustomersUsersEmploymentResponse, Error>
> & {
  userId?: string;
};

// https://arctfrex.apidog.io/api-10313430
export const useCustomersUsersEmployment = ({
  userId,
  ...options
}: Options) => {
  return useQuery({
    ...options,
    queryKey: ["customers-users-employment", userId],
    queryFn: async () => {
      const { data } = await axios.get<CustomersUsersEmploymentResponse>(
        ENDPOINT + "/" + userId
      );

      return data;
    },
  });
};
