import {
  UseMutationOptions,
  UseQueryOptions,
  useMutation,
  useQuery,
} from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/finance";

// Generated by https://quicktype.io
export interface Finance {
  userid: string;
  source_income: string;
  yearly_income_amount: string;
  yearly_additional_income_amount: string;
  estimation_wealth_amount: string;
  taxable_object_sales_value: string;
  deposito: string;
  currency: string;
  bank_name: string;
  bank_account_number: string;
  bank_beneficiary_name: string;
  bank_account_type: string;
  investment_goals: string;
  investment_experience: string;
  is_active: boolean;
  CreatedBy: string;
  CreatedAt: string;
  ModifiedBy: string;
  ModifiedAt: string;
}

export type CustomersUsersFinanceResponse = Finance;

type Options = Partial<
  UseQueryOptions<CustomersUsersFinanceResponse, Error>
> & {
  userId?: string;
};

// https://arctfrex.apidog.io/api-10313431
export const useCustomersUsersFinance = ({ userId, ...options }: Options) => {
  return useQuery({
    ...options,
    queryKey: ["customers-users-finance", userId],
    queryFn: async () => {
      const { data } = await axios.get<CustomersUsersFinanceResponse>(
        ENDPOINT + "/" + userId
      );

      return data;
    },
  });
};

export const useCustomersUsersFinanceMutation = ({
  userId,
  ...options
}: UseMutationOptions<any, Error, any> & { userId: string }) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<any>(ENDPOINT + "/" + userId, payload);

      return data;
    },
    ...options,
  });
};
