import {
  UseMutationOptions,
  UseQueryOptions,
  useMutation,
  useQuery,
} from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/profile";

// Generated by https://quicktype.io

export interface CustomersUsersProfileResponse {
  message: string;
  data: Profile;
  time: string;
}

export interface Profile {
  user_id: string;
  full_name: string;
  mobile_phone: string;
  home_phone: string;
  fax_number: string;
  gender: string;
  martial_status: string;
  place_of_birth: string;
  date_of_birth: Date;
  nationality: string;
  mother_maiden: string;
  ktp_number: string;
  identity_type: string;
  npwp_number: string;
  ktp_photo: string;
  selfie_photo: string;
  npwp_photo: string;
  additional_document_photo: string;
  declaration_video: string;
  dom_postal_code: string;
}

type Options = Partial<
  UseQueryOptions<CustomersUsersProfileResponse, Error>
> & {
  userId?: string;
};

// https://arctfrex.apidog.io/api-10313428
export const useCustomersUsersProfile = ({ userId, ...options }: Options) => {
  return useQuery({
    ...options,
    queryKey: ["customers-users-profile", userId],
    queryFn: async () => {
      const { data } = await axios.get<CustomersUsersProfileResponse>(
        ENDPOINT + "/" + userId
      );

      return data;
    },
  });
};

export const useCustomersUsersProfileMutation = ({
  userId,
  ...options
}: UseMutationOptions<any, Error, any> & { userId: string }) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<any>(ENDPOINT + "/" + userId, payload);

      return data;
    },
    ...options,
  });
};
