import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/profile";

// Generated by https://quicktype.io

export interface Profile {
  userid: string;
  gender: string;
  martial_status: string;
  place_of_birth: string;
  date_of_birth: string;
  nationality: string;
  mother_maiden: string;
  ktp_number: string;
  npwp_number: string;
  ktp_photo: string;
  selfie_photo: string;
  is_active: boolean;
  npwp_photo: string;
  additional_document_photo: string;
  declaration_video: string;
  CreatedBy: string;
  CreatedAt: string;
  ModifiedBy: string;
  ModifiedAt: string;
}

export type CustomersUsersProfileResponse = Profile;

type Options = Partial<
  UseQueryOptions<CustomersUsersProfileResponse, Error>
> & {
  userId?: string;
};

// https://arctfrex.apidog.io/api-10313428
export const useCustomersUsersProfile = ({ userId, ...options }: Options) => {
  return useQuery({
    ...options,
    queryKey: ["customers-users-profile", userId],
    queryFn: async () => {
      const { data } = await axios.get<CustomersUsersProfileResponse>(
        ENDPOINT + "/" + userId
      );

      return data;
    },
  });
};
