import {
  UseMutationOptions,
  UseQueryOptions,
  useMutation,
  useQuery,
} from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/customers/users/register";

// Generated by https://quicktype.io
export type CustomersUsersRegisterData = {};

export type CustomersUsersRegisterVariables = {
  customer_name: string;
  email: string;
  mobilephone: string;
};

type Options = Partial<
  UseMutationOptions<
    CustomersUsersRegisterData,
    Error,
    CustomersUsersRegisterVariables
  >
>;

// https://arctfrex.apidog.io/api-10313428
export const useCustomersUsersRegister = (options: Options = {}) => {
  return useMutation({
    ...options,
    mutationFn: async (payload: CustomersUsersRegisterVariables) => {
      const { data } = await axios.post<CustomersUsersRegisterData>(
        ENDPOINT,
        payload
      );

      return data;
    },
  });
};
