import {
  UseMutationOptions,
  UseQueryOptions,
  useMutation,
  useQuery,
} from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/account/pending/approval";

// Generated by https://quicktype.io
export interface AccountPendingApprovalRequest {
  accountid: string;
  decision: string;
  userlogin: string;
}

// Generated by https://quicktype.io
export interface AccountPendingApprovalResponse {
  message: string;
  data: null;
  time: string;
}

// https://arctfrex.apidog.io/api-10321359
export const useAccountPendingApproval = (
  options: UseMutationOptions<
    AccountPendingApprovalResponse,
    Error,
    AccountPendingApprovalRequest
  >
) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<AccountPendingApprovalResponse>(
        ENDPOINT,
        payload
      );

      return data;
    },
    ...options,
  });
};
