import { UseMutationOptions, useMutation } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/withdrawal/pending/approval";

// Generated by https://quicktype.io
export interface WithdrawalPendingApprovalRequest {
  withdrawalid: string;
  decision: string;
  userlogin: string;
}

// Generated by https://quicktype.io
export interface WithdrawalPendingApprovalResponse {
  message: string;
  data: null;
  time: string;
}

// https://arctfrex.apidog.io/api-10321359
export const useWithdrawalPendingApproval = (
  options: UseMutationOptions<
    WithdrawalPendingApprovalResponse,
    Error,
    WithdrawalPendingApprovalRequest
  >
) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<WithdrawalPendingApprovalResponse>(
        ENDPOINT,
        payload
      );

      return data;
    },
    ...options,
  });
};
