import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";
import { ApprovalStatus } from "@/models/account";

const ENDPOINT = "/backoffice/withdrawal/pending";

// Generated by https://quicktype.io
interface Withdrawal {
  withdrawalid: string;
  accountid: string;
  userid: string;
  name: string;
  email: string;
  amount: number;
  bank_name: string;
  bank_account_number: string;
  bank_beneficiary_name: string;
  approval_status: ApprovalStatus;
}

export type WithdrawalPendingDetailResponse = {
  data: Withdrawal;
  message: string;
};

type Options = Partial<
  UseQueryOptions<WithdrawalPendingDetailResponse, Error>
> & {
  withdrawalid?: string;
};

// https://arctfrex.apidog.io/api-10313428
export const useWithdrawalPendingDetail = ({
  withdrawalid,
  ...options
}: Options) => {
  return useQuery({
    ...options,
    queryKey: ["withdrawal-pending-detail", withdrawalid],
    queryFn: async () => {
      const { data } = await axios.get<WithdrawalPendingDetailResponse>(
        ENDPOINT + "/" + withdrawalid
      );

      return data;
    },
  });
};
