import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/withdrawal/pending/spa";

// Generated by https://quicktype.io
export interface WithdrawalPendingSpaResponse {
  message: string;
  data: Withdrawal[];
  pagination: Pagination;
  time: string;
}

export interface Withdrawal {
  withdrawal_id: string;
  account_id: string;
  user_id: string;
  name: string;
  email: string;
  amount: number;
  amount_usd: number;
  approval_status: number | string;
  created_at: Date;
  bank_name: string;
  meta_login_id: number;
  finance_by: string;
}

export interface Pagination {
  sorter: string;
  total: number;
  page_size: number;
  current_page: number;
}

type Options = Partial<UseQueryOptions<WithdrawalPendingSpaResponse, Error>> &
  Partial<Pagination> & {
    menutype?: string;
  };

// https://arctfrex.apidog.io/api-16510282
export const useWithdrawalPendingSpaQuery = ({
  menutype,
  current_page,
  page_size,
  ...options
}: Options) => {
  return useQuery({
    queryKey: [ENDPOINT, menutype, current_page, page_size],
    queryFn: async () => {
      const { data } = await axios.get<WithdrawalPendingSpaResponse>(
        ENDPOINT + "/" + menutype,
        {
          params: {
            current_page,
            page_size,
          },
        }
      );

      return data;
    },
    ...options,
  });
};
