import { UseMutationOptions, useMutation } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/storages/upload";

// Generated by https://quicktype.io
export interface StorageUploadResponse {
  message: string;
  data: null;
  time: string;
}

// https://arctfrex.apidog.io/api-12462737
export const useStorageUpload = (
  options?: UseMutationOptions<StorageUploadResponse, Error, FormData>
) => {
  return useMutation({
    mutationFn: async (payload) => {
      const { data } = await axios.post<StorageUploadResponse>(
        ENDPOINT,
        payload,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      return data;
    },
    ...options,
  });
};
