import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import axios from "@/libs/axios";

const ENDPOINT = "/backoffice/deposit/credit/multi";

// Generated by https://quicktype.io
export interface DepositCreditMultiResponse {
  message: string;
  data: Data;
  time: string;
}

export interface Data {
  deposit_id: string;
  account_id: string;
  user_id: string;
  name: string;
  email: string;
  amount: number;
  amount_usd: number;
  bank_name: string;
  bank_account_number: string;
  bank_beneficiary_name: string;
  deposit_photo: string;
  approval_status: number | string;
}

type Options = Partial<UseQueryOptions<DepositCreditMultiResponse, Error>> & {
  menutype?: string;
  depositid?: string;
};

// https://arctfrex.apidog.io/api-16495989
export const useDepositCreditMultiMenuTypeDepositIdQuery = ({
  menutype,
  depositid,
  ...options
}: Options) => {
  return useQuery({
    queryKey: [ENDPOINT, menutype, depositid],
    queryFn: async () => {
      const { data } = await axios.get<DepositCreditMultiResponse>(
        ENDPOINT + "/" + menutype + "/" + depositid
      );

      return data;
    },
    ...options,
  });
};
